os:
  - linux

language: python

python:
    - 3.7

sudo: required
        
branches:
  only:
    - gh-pages
    - /.*/

cache: pip

# Builds Test
env:
    global:
        - USR_NAME="OlafFilies"
        - USR_EMAIL="Olaf.Filies@infineon.com"
    matrix:
        - PLATFORMIO_CI_SRC=examples/basicTest
        - PLATFORMIO_CI_SRC=examples/rampSpeedTest
        - PLATFORMIO_CI_SRC=examples/control2Motors 
        - PLATFORMIO_CI_SRC=examples/speedControl

install: 
  - pip install -U platformio==4.1.0
  - platformio platform install -f infineonxmc@1.1.3
  - platformio platform install -f atmelavr@2.0.0

script: 
  - platformio ci --lib="." --board=xmc1100_boot_kit --board=xmc4700_relax_kit --board=uno

jobs:
  include:   
    - stage: "Deploy" 
      name: "GitHub Pages Deployment"
      if: tag IS present
      addons:
        apt:
            packages:
            - doxygen
            - graphviz
            sources:
                - ubuntu-toolchain-r-test
      install:
        - git clone https://github.com/Infineon/InfineonDoxyGenerator.git --branch v.0.2.1
      script: 
        - cd InfineonDoxyGenerator

        - python doxyifx.py html
        - python doxyifx.py release $GH_USER $GH_PASS_TOKEN

    - stage: "devel" 
      name: "GitHub Pages Deployment"
      if: tag IS present
      addons:
        apt:
            packages:
            - doxygen
            - graphviz
            sources:
                - ubuntu-toolchain-r-test
      install:
        - git clone https://github.com/Infineon/InfineonDoxyGenerator.git --branch v.0.2.1
      script: 
        - cd InfineonDoxyGenerator

        - python doxyifx.py html
        - python doxyifx.py release $GH_USER $GH_PASS_TOKEN

after_success:
  
  
